spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3308/jsonmapping?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
